// Code generated by protoc-gen-go.
// source: movie.proto
// DO NOT EDIT!

/*
Package movies is a generated protocol buffer package.

It is generated from these files:
	movie.proto

It has these top-level messages:
	Movie
	Movies
	ReqMovie
*/
package movies

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Id            int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Filename      string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Playtime      int32  `protobuf:"varint,4,opt,name=playtime" json:"playtime,omitempty"`
	Photodatetime uint32 `protobuf:"varint,5,opt,name=photodatetime" json:"photodatetime,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Movies struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *Movies) Reset()                    { *m = Movies{} }
func (m *Movies) String() string            { return proto.CompactTextString(m) }
func (*Movies) ProtoMessage()               {}
func (*Movies) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Movies) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type ReqMovie struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReqMovie) Reset()                    { *m = ReqMovie{} }
func (m *ReqMovie) String() string            { return proto.CompactTextString(m) }
func (*ReqMovie) ProtoMessage()               {}
func (*ReqMovie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Movie)(nil), "movies.Movie")
	proto.RegisterType((*Movies)(nil), "movies.Movies")
	proto.RegisterType((*ReqMovie)(nil), "movies.ReqMovie")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MovieService service

type MovieServiceClient interface {
	GetPerson(ctx context.Context, in *ReqMovie, opts ...grpc.CallOption) (*Movie, error)
	GetPersons(ctx context.Context, in *ReqMovie, opts ...grpc.CallOption) (*Movies, error)
}

type movieServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovieServiceClient(cc *grpc.ClientConn) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) GetPerson(ctx context.Context, in *ReqMovie, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := grpc.Invoke(ctx, "/movies.MovieService/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) GetPersons(ctx context.Context, in *ReqMovie, opts ...grpc.CallOption) (*Movies, error) {
	out := new(Movies)
	err := grpc.Invoke(ctx, "/movies.MovieService/GetPersons", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieService service

type MovieServiceServer interface {
	GetPerson(context.Context, *ReqMovie) (*Movie, error)
	GetPersons(context.Context, *ReqMovie) (*Movies, error)
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMovie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movies.MovieService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetPerson(ctx, req.(*ReqMovie))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_GetPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMovie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movies.MovieService/GetPersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetPersons(ctx, req.(*ReqMovie))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "movies.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _MovieService_GetPerson_Handler,
		},
		{
			MethodName: "GetPersons",
			Handler:    _MovieService_GetPersons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x49, 0x67, 0xca, 0x76, 0x66, 0x87, 0x1c, 0xbc, 0x08, 0xbd, 0x0a, 0x43, 0x21, 0x17,
	0x12, 0x61, 0x3e, 0x84, 0x57, 0x82, 0xc4, 0x27, 0xa8, 0xf6, 0x88, 0x81, 0x74, 0xa9, 0x4d, 0x18,
	0xf8, 0x0c, 0xbe, 0xb4, 0xec, 0xcc, 0x16, 0x0a, 0xbd, 0xcb, 0x97, 0xff, 0x3f, 0x7f, 0xfe, 0x1c,
	0xd8, 0x76, 0xf1, 0xe4, 0xc9, 0xf6, 0x43, 0xcc, 0x11, 0x4b, 0x86, 0xb4, 0xff, 0x15, 0x20, 0x5f,
	0xce, 0x47, 0xdc, 0x41, 0xe1, 0x5b, 0x25, 0xb4, 0x30, 0xd2, 0x15, 0xbe, 0xc5, 0x1a, 0xd6, 0x9f,
	0x3e, 0xd0, 0xb1, 0xe9, 0x48, 0x15, 0x5a, 0x98, 0x8d, 0x9b, 0x18, 0x6f, 0x41, 0x66, 0x9f, 0x03,
	0xa9, 0x15, 0x0b, 0x17, 0x38, 0x4f, 0xf4, 0xa1, 0xf9, 0xc9, 0xbe, 0x23, 0x75, 0xc5, 0x39, 0x13,
	0xe3, 0x1d, 0x54, 0xfd, 0x57, 0xcc, 0xb1, 0x6d, 0x32, 0xb1, 0x41, 0x6a, 0x61, 0x2a, 0x37, 0xbf,
	0xdc, 0x3f, 0x42, 0xc9, 0x65, 0x12, 0xde, 0xc3, 0x7f, 0x43, 0x25, 0xf4, 0xca, 0x6c, 0x0f, 0x95,
	0xbd, 0xa0, 0x65, 0xdd, 0x8d, 0xf5, 0x6b, 0x58, 0x3b, 0xfa, 0x5e, 0xfc, 0xc0, 0x21, 0xc0, 0x35,
	0x0b, 0x6f, 0x34, 0x9c, 0xfc, 0x07, 0xe1, 0x03, 0x6c, 0x9e, 0x29, 0xbf, 0xd2, 0x90, 0xe2, 0x11,
	0x6f, 0xc6, 0xbc, 0x71, 0xbc, 0x9e, 0xbf, 0x80, 0x16, 0x60, 0x72, 0xa7, 0x05, 0xfb, 0x6e, 0x66,
	0x4f, 0xef, 0x25, 0xef, 0xf5, 0xe9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xba, 0xa9, 0x1b, 0x66,
	0x01, 0x00, 0x00,
}
