// Code generated by protoc-gen-go.
// source: movie_s2p.proto
// DO NOT EDIT!

/*
Package moviess2p is a generated protocol buffer package.

It is generated from these files:
	movie_s2p.proto

It has these top-level messages:
	Movie
	Movies
	MovieSkey
*/
package moviess2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Skey          string `protobuf:"bytes,1,opt,name=skey" json:"skey,omitempty"`
	Filename      string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Playtime      int32  `protobuf:"varint,4,opt,name=playtime" json:"playtime,omitempty"`
	Photodatetime uint32 `protobuf:"varint,5,opt,name=photodatetime" json:"photodatetime,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Movies struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *Movies) Reset()                    { *m = Movies{} }
func (m *Movies) String() string            { return proto.CompactTextString(m) }
func (*Movies) ProtoMessage()               {}
func (*Movies) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Movies) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type MovieSkey struct {
	Skey string `protobuf:"bytes,1,opt,name=skey" json:"skey,omitempty"`
}

func (m *MovieSkey) Reset()                    { *m = MovieSkey{} }
func (m *MovieSkey) String() string            { return proto.CompactTextString(m) }
func (*MovieSkey) ProtoMessage()               {}
func (*MovieSkey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Movie)(nil), "moviess2p.Movie")
	proto.RegisterType((*Movies)(nil), "moviess2p.Movies")
	proto.RegisterType((*MovieSkey)(nil), "moviess2p.MovieSkey")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MovieS2PService service

type MovieS2PServiceClient interface {
	GetPerson(ctx context.Context, in *MovieSkey, opts ...grpc.CallOption) (*Movie, error)
	GetPersons(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movies, error)
}

type movieS2PServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovieS2PServiceClient(cc *grpc.ClientConn) MovieS2PServiceClient {
	return &movieS2PServiceClient{cc}
}

func (c *movieS2PServiceClient) GetPerson(ctx context.Context, in *MovieSkey, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := grpc.Invoke(ctx, "/moviess2p.MovieS2PService/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieS2PServiceClient) GetPersons(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movies, error) {
	out := new(Movies)
	err := grpc.Invoke(ctx, "/moviess2p.MovieS2PService/GetPersons", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieS2PService service

type MovieS2PServiceServer interface {
	GetPerson(context.Context, *MovieSkey) (*Movie, error)
	GetPersons(context.Context, *Movie) (*Movies, error)
}

func RegisterMovieS2PServiceServer(s *grpc.Server, srv MovieS2PServiceServer) {
	s.RegisterService(&_MovieS2PService_serviceDesc, srv)
}

func _MovieS2PService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieSkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieS2PServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviess2p.MovieS2PService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieS2PServiceServer).GetPerson(ctx, req.(*MovieSkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieS2PService_GetPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieS2PServiceServer).GetPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviess2p.MovieS2PService/GetPersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieS2PServiceServer).GetPersons(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieS2PService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moviess2p.MovieS2PService",
	HandlerType: (*MovieS2PServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _MovieS2PService_GetPerson_Handler,
		},
		{
			MethodName: "GetPersons",
			Handler:    _MovieS2PService_GetPersons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("movie_s2p.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xbb, 0x2d, 0x76, 0x64, 0x59, 0x1d, 0xf6, 0x10, 0x7a, 0xb1, 0x14, 0x0f, 0x39,
	0x15, 0xcc, 0x3e, 0x84, 0x27, 0x61, 0xe9, 0x3e, 0x80, 0x54, 0x1d, 0x31, 0xd8, 0x6e, 0x42, 0x27,
	0x2c, 0xf4, 0x29, 0x7c, 0x65, 0xe9, 0x54, 0x0a, 0x6e, 0xbd, 0xe5, 0xff, 0xfe, 0x7f, 0x26, 0x7f,
	0x02, 0xdb, 0xce, 0x9f, 0x1d, 0xbd, 0xb0, 0x0d, 0x55, 0xe8, 0x7d, 0xf4, 0x98, 0x09, 0x60, 0xb6,
	0xa1, 0xfc, 0x56, 0x90, 0x3c, 0x8f, 0x0a, 0x11, 0xd6, 0xfc, 0x45, 0x83, 0x56, 0x85, 0x32, 0x59,
	0x2d, 0x67, 0xcc, 0xe1, 0xfa, 0xc3, 0xb5, 0x74, 0x6a, 0x3a, 0xd2, 0x57, 0xc2, 0x67, 0x8d, 0x3b,
	0x48, 0xa2, 0x8b, 0x2d, 0xe9, 0x95, 0x18, 0x93, 0x18, 0x27, 0x42, 0xdb, 0x0c, 0xd1, 0x75, 0xa4,
	0xd7, 0x85, 0x32, 0x49, 0x3d, 0x6b, 0x7c, 0x80, 0x4d, 0xf8, 0xf4, 0xd1, 0xbf, 0x37, 0x91, 0x24,
	0x90, 0x14, 0xca, 0x6c, 0xea, 0xbf, 0xb0, 0xb4, 0x90, 0x4a, 0x21, 0x46, 0x03, 0xe9, 0x54, 0x54,
	0xab, 0x62, 0x65, 0x6e, 0xec, 0x6d, 0x35, 0xf7, 0xae, 0x24, 0x52, 0xff, 0xfa, 0xe5, 0x3d, 0x64,
	0x02, 0x8e, 0x63, 0xe9, 0x7f, 0x1e, 0x62, 0x07, 0xd8, 0x4e, 0x01, 0x7b, 0x38, 0x52, 0x7f, 0x76,
	0x6f, 0x84, 0x7b, 0xc8, 0x9e, 0x28, 0x1e, 0xa8, 0x67, 0x7f, 0xc2, 0xdd, 0xe5, 0xea, 0x71, 0x53,
	0xbe, 0xb8, 0x10, 0x1f, 0x01, 0xe6, 0x21, 0xc6, 0x85, 0x9f, 0xdf, 0x5d, 0x12, 0x7e, 0x4d, 0xe5,
	0xcf, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xf1, 0xfb, 0x72, 0x86, 0x01, 0x00, 0x00,
}
