// Code generated by protoc-gen-go.
// source: movie_c2s.proto
// DO NOT EDIT!

/*
Package moviesc2s is a generated protocol buffer package.

It is generated from these files:
	movie_c2s.proto

It has these top-level messages:
	Movie
	Movies
	MovieSkey
*/
package moviesc2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Skey          string `protobuf:"bytes,1,opt,name=skey" json:"skey,omitempty"`
	Filename      string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Playtime      int32  `protobuf:"varint,4,opt,name=playtime" json:"playtime,omitempty"`
	Photodatetime uint32 `protobuf:"varint,5,opt,name=photodatetime" json:"photodatetime,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Movies struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *Movies) Reset()                    { *m = Movies{} }
func (m *Movies) String() string            { return proto.CompactTextString(m) }
func (*Movies) ProtoMessage()               {}
func (*Movies) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Movies) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type MovieSkey struct {
	Skey string `protobuf:"bytes,1,opt,name=skey" json:"skey,omitempty"`
}

func (m *MovieSkey) Reset()                    { *m = MovieSkey{} }
func (m *MovieSkey) String() string            { return proto.CompactTextString(m) }
func (*MovieSkey) ProtoMessage()               {}
func (*MovieSkey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Movie)(nil), "moviesc2s.Movie")
	proto.RegisterType((*Movies)(nil), "moviesc2s.Movies")
	proto.RegisterType((*MovieSkey)(nil), "moviesc2s.MovieSkey")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MovieC2SService service

type MovieC2SServiceClient interface {
	GetMovie(ctx context.Context, in *MovieSkey, opts ...grpc.CallOption) (*Movie, error)
	GetMovies(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movies, error)
}

type movieC2SServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovieC2SServiceClient(cc *grpc.ClientConn) MovieC2SServiceClient {
	return &movieC2SServiceClient{cc}
}

func (c *movieC2SServiceClient) GetMovie(ctx context.Context, in *MovieSkey, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := grpc.Invoke(ctx, "/moviesc2s.MovieC2SService/GetMovie", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieC2SServiceClient) GetMovies(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Movies, error) {
	out := new(Movies)
	err := grpc.Invoke(ctx, "/moviesc2s.MovieC2SService/GetMovies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieC2SService service

type MovieC2SServiceServer interface {
	GetMovie(context.Context, *MovieSkey) (*Movie, error)
	GetMovies(context.Context, *Movie) (*Movies, error)
}

func RegisterMovieC2SServiceServer(s *grpc.Server, srv MovieC2SServiceServer) {
	s.RegisterService(&_MovieC2SService_serviceDesc, srv)
}

func _MovieC2SService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieSkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieC2SServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesc2s.MovieC2SService/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieC2SServiceServer).GetMovie(ctx, req.(*MovieSkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieC2SService_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieC2SServiceServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesc2s.MovieC2SService/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieC2SServiceServer).GetMovies(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieC2SService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moviesc2s.MovieC2SService",
	HandlerType: (*MovieC2SServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _MovieC2SService_GetMovie_Handler,
		},
		{
			MethodName: "GetMovies",
			Handler:    _MovieC2SService_GetMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("movie_c2s.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x65, 0xda, 0x44, 0xcd, 0xa0, 0xaa, 0x30, 0xea, 0xc2, 0xca, 0x06, 0x2b, 0x62, 0xe1,
	0x55, 0x84, 0xcc, 0x11, 0x58, 0xb0, 0x62, 0xe3, 0x1c, 0x00, 0x85, 0x30, 0x08, 0x8b, 0x04, 0x47,
	0xb5, 0x55, 0xd4, 0x53, 0x70, 0x65, 0xe4, 0x09, 0x44, 0xa2, 0xed, 0x2e, 0xff, 0xfd, 0x3f, 0x93,
	0x3f, 0x86, 0xcd, 0xe0, 0xf7, 0x8e, 0x9e, 0x3b, 0x13, 0xea, 0x71, 0xe7, 0xa3, 0xc7, 0x82, 0x41,
	0xe8, 0x4c, 0xa8, 0xbe, 0x05, 0x64, 0x4f, 0x49, 0x21, 0xc2, 0x32, 0x7c, 0xd0, 0x41, 0x0a, 0x25,
	0x74, 0x61, 0xf9, 0x1b, 0x4b, 0x58, 0xbd, 0xb9, 0x9e, 0x3e, 0xdb, 0x81, 0xe4, 0x05, 0xf3, 0x59,
	0xe3, 0x16, 0xb2, 0xe8, 0x62, 0x4f, 0x72, 0xc1, 0xc6, 0x24, 0xd2, 0xc4, 0xd8, 0xb7, 0x87, 0xe8,
	0x06, 0x92, 0x4b, 0x25, 0x74, 0x66, 0x67, 0x8d, 0xb7, 0xb0, 0x1e, 0xdf, 0x7d, 0xf4, 0xaf, 0x6d,
	0x24, 0x0e, 0x64, 0x4a, 0xe8, 0xb5, 0xfd, 0x0f, 0x2b, 0x03, 0x39, 0x17, 0x0a, 0xa8, 0x21, 0x9f,
	0x8a, 0x4a, 0xa1, 0x16, 0xfa, 0xd2, 0x5c, 0xd5, 0x73, 0xef, 0x9a, 0x23, 0xf6, 0xd7, 0xaf, 0x6e,
	0xa0, 0x60, 0xd0, 0xa4, 0xd2, 0x67, 0x0e, 0x31, 0x5f, 0xb0, 0xe1, 0xc0, 0x83, 0x69, 0x1a, 0xda,
	0xed, 0x5d, 0x47, 0x68, 0x60, 0xf5, 0x48, 0x71, 0xba, 0x7d, 0x7b, 0xbc, 0x39, 0x2d, 0x2a, 0x4f,
	0xfe, 0x87, 0x77, 0x50, 0xfc, 0xcd, 0x04, 0x3c, 0xb1, 0xcb, 0xeb, 0x63, 0x12, 0x5e, 0x72, 0x7e,
	0xf1, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xdf, 0x96, 0x02, 0x84, 0x01, 0x00, 0x00,
}
